services:
  app:
    build:
      context: .
      dockerfile: spring.Dockerfile

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ./proxy/server.key
        target: /etc/nginx/conf.d/server.key
      - type: bind
        source: ./proxy/server.cert
        target: /etc/nginx/conf.d/server.cert
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
