spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: sa
    url: jdbc:sqlite:./database.db
  sql:
    init:
      platform: sqlite
logging:
  level:
    org:
      springframework:
        security: DEBUG